spring:
  shardingsphere:
    props:
      # 打印sql
      sql-show: true
      # 配置是否基于密文列查询
      query-with-cipher-column: true
    # 配置数据源
    datasource:
      # 配置公共数据源信息
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      names: demo0
      demo0:
        jdbc-url: jdbc:mysql://localhost:3306/demo0?serverTimezone=GMT%2B8
        username: root
        password: 1234

    # 规则配置
    rules:
      encrypt:
        # 表配置
        tables:
          tbl_user:
            columns:
              mobile:
                cipher-column: mobile_encrypt
                plain-column: mobile
                encryptor-name: aes-algorithm
              id_card:
                cipher-column: id_card_encrypt
                plain-column: id_card
                encryptor-name: aes-algorithm
          tbl_enterprise:
            columns:
              contact_mobile:
                cipher-column: contact_mobile_encrypt
                plain-column: contact_mobile
                encryptor-name: aes-algorithm
        # 加密算法配置
        encryptors:
          aes-algorithm:
            type: AES
            props:
              aes-key-value: "X3ewzLzYBKzM9vwn"

